version: "3.9"
services:
    frontend:
        container_name: drinkdispenser_frontend
        ports: 
          - "8080:3000"
        build:
            context: ./frontend
            dockerfile: Dockerfile
    backend:
        container_name: drinkdispenser_backend
        privileged: true
        ports: 
          - "8000:8000"
        build:
            context: ./backend
            dockerfile: Dockerfile
